/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#fdf9f4',
        'surface-dim': '#ddd9d5',
        'surface-bright': '#fdf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f7f3ee',
        'surface-container': '#f1ede8',
        'surface-container-high': '#ebe8e3',
        'surface-container-highest': '#e6e2dd',
        'on-surface': '#1c1c19',
        'on-surface-variant': '#51443c',
        'inverse-surface': '#31302d',
        'inverse-on-surface': '#f4f0eb',
        outline: '#83746b',
        'outline-variant': '#d5c3b9',
        'surface-tint': '#815434',
        primary: '#7e5232',
        'on-primary': '#ffffff',
        'primary-container': '#9a6a48',
        'on-primary-container': '#fffbff',
        'inverse-primary': '#f5ba93',
        secondary: '#785746',
        'on-secondary': '#ffffff',
        'secondary-container': '#ffd4be',
        'on-secondary-container': '#7a5a48',
        tertiary: '#7c541d',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#986c33',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#fdf9f4',
        'on-background': '#1c1c19',
        'surface-variant': '#e6e2dd',
        'toasted-cream': '#F2EAE0',
        'dusty-peach': '#E8C9B5',
        espresso: '#2C1F18',
        'warm-white': '#FFFDF9',
      },
      fontFamily: {
        display: ['Cormorant Garamond', 'serif'],
        body: ['Jost', 'sans-serif'],
      },
      spacing: {
        'section-v-desktop': '120px',
        'section-v-mobile': '72px',
        'overlap-offset': '60px',
        'margin-mobile': '24px',
        'gutter': '80px',
        'desktop-max-width': '1280px',
      },
    },
  },
  plugins: [],
}
